# fly.toml file generated for atcms-replibyte on 2022-08-08T22:35:50-06:00

app = "atcms-replibyte"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
TZ = "America/Denver"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
